version: "3.9"

services:
  go-backend:
    build:
      context: ./back/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./back:/app/go
    tty: true

  frontend:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front:/app/front
    ports:
      - 3000:3000 
    tty: true
    
  pgsql_db:
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME}
    build:
      context: ./back/db/
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${USER_NAME}
      - POSTGRES_PASSWORD=${USER_PASS}
    volumes:
      - db_vol:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db_vol:
