version: "3.9"

services:
  go-backend:
    build:
      context: ./dockerfile/backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./back:/app/go
    tty: true
    depends_on:
      - pgsql_db

  frontend:
    build:
      context: ./dockerfile/frontend
      dockerfile: Dockerfile
    volumes:
      - ./front:/app/front
    ports:
      - 3000:3000 
    tty: true
    
  pgsql_db:
    container_name: ${CONTAINER_NAME}
    build:
      context: ./dockerfile/db/
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=${USER_NAME}
      - POSTGRES_PASSWORD=${USER_PASS}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    volumes:
      - db_vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - admin_vol:/var/lib/pgadmin
    depends_on:
      - pgsql_db

volumes:
  db_vol:
  admin_vol:
