version: "3.9"

services:
  go-backend:
    build:
      context: ./back/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./back:/app/go
    tty: true
  
  frontend:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front:/app/front
    ports:
      - 3000:3000 
